services:
  pythonapp:
    build: 
       context: ./
      dockerfile: Dockerfile_python
    command: sh -c "sleep 10s ; python3 ./hello_world.py"
    depends_on:
      - mysql

  mysql:
    build: 
       context: ./
      dockerfile: Dockerfile_mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
